// <auto-generated />
namespace LibraryManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class BookAndMemberInitialState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookAndMemberInitialState));
        
        string IMigrationMetadata.Id
        {
            get { return "201912111241227_BookAndMemberInitialState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
